"""학교 페이지에 정적 학사일정 콘텐츠를 굽는다(AdSense/SEO용).

각 학교의 라이브 `.ics` 피드(`/calendar/{slug}.ics`)를 받아 파싱한 뒤,
`docs/s/{slug}.html` 의 마커(`<!-- SCHEDULE:START -->` … `<!-- SCHEDULE:END -->`)
사이에 정적 일정 표 HTML을 주입한다. 멱등 — 매 실행마다 마커 사이를 새로 교체.

크롤러가 보는 정적 HTML에 실제 일정 텍스트가 들어가도록 하는 게 목적.
런타임 `#upcomingRoot` JS 위젯(다가오는 일정 D-day)은 그대로 두고 공존시킨다.

실행:  python -m scripts.build_school_pages
배포 전 이 스크립트를 돌리고 `git diff docs/s/` 를 검토한 뒤 `npx wrangler deploy`.
"""
from __future__ import annotations

import datetime as dt
import html
import logging
import re
import urllib.error
import urllib.request
from pathlib import Path

from app.categories import CATEGORIES, CATEGORY_BY_SLUG
from scripts.seed_schools import SCHOOLS

logging.basicConfig(level=logging.INFO, format="%(levelname)s :: %(message)s")
log = logging.getLogger("build_school_pages")

FEED_BASE = "https://campus-cal.com/calendar"
DOCS_S = Path(__file__).resolve().parent.parent / "docs" / "s"
ANCHOR = '<div id="upcomingRoot"></div>'
MARKER_RE = re.compile(r"<!-- SCHEDULE:START.*?SCHEDULE:END -->", re.DOTALL)

# DTEND는 비포함(exclusive) — subscribe.js 의 fmtRange 와 동일한 규칙.
DAY = dt.timedelta(days=1)


def academic_year(today: dt.date) -> int:
    """한국 학년도: 3월~다음해 2월. 3월 이전이면 전 학년도."""
    return today.year if today.month >= 3 else today.year - 1


def fetch_ics(slug: str) -> str | None:
    url = f"{FEED_BASE}/{slug}.ics"
    req = urllib.request.Request(url, headers={"User-Agent": "campus-ical-build/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            if resp.status != 200:
                log.warning("%s: HTTP %s — skip", slug, resp.status)
                return None
            return resp.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as e:
        log.warning("%s: HTTP %s — skip", slug, e.code)
    except (urllib.error.URLError, TimeoutError, OSError) as e:
        log.warning("%s: fetch 실패(%s) — skip", slug, e)
    return None


def _ymd(s: str) -> dt.date:
    return dt.date(int(s[:4]), int(s[4:6]), int(s[6:8]))


def parse_ics(text: str) -> list[dict]:
    """subscribe.js parseIcs(L415~) 의 파싱 규칙을 그대로 미러."""
    out: list[dict] = []
    for block in text.split("BEGIN:VEVENT")[1:]:
        sm = re.search(r"\nSUMMARY:(.*)", block)
        ds = re.search(r"DTSTART[^:\n]*:(\d{8})", block)
        if not sm or not ds:
            continue
        de = re.search(r"DTEND[^:\n]*:(\d{8})", block)
        cm = re.search(r"\nCATEGORIES:(.*)", block)
        summary = re.sub(r"\\([,;\\])", r"\1", sm.group(1)).strip()
        start = _ymd(ds.group(1))
        end = _ymd(de.group(1)) if de else start
        cats = (
            [c.strip() for c in cm.group(1).strip().split(",") if c.strip()]
            if cm else []
        )
        out.append({"summary": summary, "start": start, "end": end, "cats": cats})
    return out


def fmt_md(d: dt.date) -> str:
    return f"{d.month}월 {d.day}일"


def fmt_range(start: dt.date, end: dt.date) -> str:
    last = end - DAY  # DTEND 비포함 → 실제 마지막 날
    return fmt_md(start) if last <= start else f"{fmt_md(start)} ~ {fmt_md(last)}"


def cat_labels(cats: list[str]) -> str:
    labels = [CATEGORY_BY_SLUG[c].label for c in cats if c in CATEGORY_BY_SLUG]
    return "·".join(labels)


def build_block(name: str, website: str, ay: int, events: list[dict]) -> str:
    # 이 학교 피드에 실제 등장한 카테고리만 — 학교마다 고유 소개 문장(중복 회피).
    present = {c for e in events for c in e["cats"]}
    present_labels = [c.label for c in CATEGORIES if c.slug in present]
    listed = ", ".join(present_labels) if present_labels else "수강신청·시험·등록금·휴학·계절학기"

    rows = []
    for e in sorted(events, key=lambda x: (x["start"], x["end"])):
        rows.append(
            "<tr>"
            f'<td class="schedule__date">{html.escape(fmt_range(e["start"], e["end"]))}</td>'
            f'<td class="schedule__name">{html.escape(e["summary"])}</td>'
            f'<td class="schedule__cat">{html.escape(cat_labels(e["cats"]))}</td>'
            "</tr>"
        )

    intro = (
        f"{html.escape(name)}의 {ay}학년도 주요 학사일정입니다. "
        f"{html.escape(listed)} 등 총 {len(events)}개 일정을 날짜순으로 정리했습니다. "
        f"모든 일정은 {html.escape(name)} 공식 학사일정을 기준으로 매일 자동 동기화되며, "
        "학교가 일정을 변경하면 구독한 캘린더에도 반영됩니다."
    )

    return (
        "<!-- SCHEDULE:START (generated by scripts/build_school_pages.py — 직접 편집 금지) -->\n"
        '<section class="schedule">\n'
        f'<h2 class="schedule__title">{ay}학년도 {html.escape(name)} 주요 학사일정</h2>\n'
        f'<p class="schedule__intro">{intro}</p>\n'
        '<table class="schedule__table">\n'
        "<thead><tr><th>기간</th><th>일정</th><th>분류</th></tr></thead>\n"
        "<tbody>\n" + "\n".join(rows) + "\n</tbody>\n"
        "</table>\n"
        f'<p class="schedule__source">출처: '
        f'<a href="{html.escape(website, quote=True)}" target="_blank" rel="noopener">'
        f"{html.escape(name)} 공식 학사일정 페이지</a></p>\n"
        "</section>\n"
        "<!-- SCHEDULE:END -->"
    )


def inject(slug: str, block: str) -> bool:
    path = DOCS_S / f"{slug}.html"
    if not path.exists():
        log.warning("%s: %s 없음 — skip", slug, path)
        return False
    htmltext = path.read_text(encoding="utf-8")
    if "SCHEDULE:START" in htmltext:
        new = MARKER_RE.sub(lambda _m: block, htmltext, count=1)
    elif ANCHOR in htmltext:
        new = htmltext.replace(ANCHOR, block + "\n" + ANCHOR, 1)
    else:
        log.warning("%s: 주입 위치(%s)도 마커도 없음 — skip", slug, ANCHOR)
        return False
    if new == htmltext:
        log.info("%s: 변경 없음", slug)
        return False
    path.write_text(new, encoding="utf-8")
    return True


def main() -> None:
    today = dt.date.today()
    ay = academic_year(today)
    ay_start = dt.date(ay, 3, 1)
    ay_end = dt.date(ay + 1, 2, 28)

    updated = skipped = 0
    for s in SCHOOLS:
        slug, name, website = s["slug"], s["name"], s["website"]
        text = fetch_ics(slug)
        if not text:
            skipped += 1
            continue
        events = parse_ics(text)
        # 학년도 창과 겹치는 일정만(이전 학년도 잔재 제거, 다년 일정 포함).
        events = [e for e in events if (e["end"] - DAY) >= ay_start and e["start"] <= ay_end]
        if not events:
            log.warning("%s: %d학년도 창 내 일정 0건 — skip", slug, ay)
            skipped += 1
            continue
        block = build_block(name, website, ay, events)
        if inject(slug, block):
            log.info("%s: %d개 일정 주입", slug, len(events))
            updated += 1
        else:
            skipped += 1

    log.info("완료 — 갱신 %d개, 건너뜀 %d개 (학년도 %d)", updated, skipped, ay)


if __name__ == "__main__":
    main()
